const measurements = {
  ounce: 'ounce',
  gram: 'gram',
  pound: 'pound',
  kilogram: 'kilogram',
  pinch: 'pinch',
  liter: 'liter',
  'fluid ounce': 'fluid ounce',
  gallon: 'gallon',
  pint: 'pint',
  quart: 'quart',
  milliliter: 'milliliter',
  drop: 'drop',
  cup: 'cup',
  tablespoon: 'tablespoon',
  teaspoon: 'teaspoon',
};
