const shopppingGroups = [
  { id: 0, name: 'baking' },
  { id: 1, name: 'beans, grains and rice' },
  { id: 2, name: 'beer' },
  { id: 3, name: 'beverages' },
  { id: 4, name: 'bread and bakery' },
  { id: 5, name: 'breakfast and cereal' },
  { id: 6, name: 'canned goods' },
  { id: 7, name: 'cheese' },
  { id: 8, name: 'cleaning' },
  { id: 9, name: 'coffee' },
  { id: 10, name: 'condiments and sauces' },
  { id: 11, name: 'cookies and snacks' },
  { id: 12, name: 'dairy' },
  { id: 13, name: 'dried fruits' },
  { id: 14, name: 'fresh fruits' },
  { id: 15, name: 'fresh spices' },
  { id: 16, name: 'floral' },
  { id: 17, name: 'frozen foods' },
  { id: 18, name: 'health and beauty' },
  { id: 20, name: 'health supplements' },
  { id: 21, name: 'international and ethnic' },
  { id: 21, name: 'jams and preserves' },
  { id: 23, name: 'juices' },
  { id: 24, name: 'kosher' },
  { id: 25, name: 'meat and poultry' },
  { id: 26, name: 'nuts' },
  { id: 27, name: 'oil and vinegar' },
  { id: 28, name: 'paper products' },
  { id: 29, name: 'pasta and noodles' },
  { id: 30, name: 'pet food' },
  { id: 31, name: 'seafood' },
  { id: 32, name: 'soups and broth' },
  { id: 33, name: 'special' },
  { id: 34, name: 'spices' },
  { id: 35, name: 'vegetables' },
  { id: 36, name: 'water' },
  { id: 37, name: 'wine and spirits' },
];
