const shopppingGroups = [
  'baking',
  'beans, grains and rice',
  'beer',
  'beverages',
  'bread and bakery',
  'breakfast and cereal',
  'canned goods',
  'cheese',
  'cleaning',
  'coffee',
  'condiments and sauces',
  'cookies and snacks',
  'dairy',
  'dried fruits',
  'fresh fruits',
  'fresh spices',
  'floral',
  'frozen foods',
  'health and beauty',
  'health supplements',
  'international and ethnic',
  'jams and preserves',
  'juices',
  'kosher',
  'meat and poultry',
  'nuts',
  'oil and vinegar',
  'paper products',
  'pasta and noodles',
  'pet food',
  'seafood',
  'soups and broth',
  'special',
  'spices',
  'vegetables'
  'water',
  'wine and spirits',
]
